---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/dbdev/retail_acls/lab_inventory/hosts.yaml"
        group_file: "/dbdev/retail_acls/lab_inventory/groups.yaml"
        defaults_file: "/dbdev/retail_acls/lab_inventory/defaults.yaml"

logging:
    enabled: True

runner:
    plugin: threaded
    options:
        num_workers: 20